---
title: "test-biomasync"
author: "CeMECA"
date: "2024-09-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
# Lista de pacotes necessários
pacotes <- c("grid", "ggspatial", "dplyr", "geosphere", "ggplot2", 
             "graphics", "httr", "magrittr", "raster", "readxl", 
             "rvest", "sf", "landscapemetrics")

# Carregar pacotes
lapply(pacotes, library, character.only = TRUE)
```

```{r}
load_codes <- function(){
  # Carregar cada arquivo com as respectivas funções
  source("./R/biomastats_sync.R")
  source("./R/check_maps.R")
  source("./R/circle_coords.R")
  source("./R/compare_shapefiles_sync.R")
  source("./R/download_maps.R")
  source("./R/download_public_gdrive_file.R")
  source("./R/get_api_values.R")
  source("./R/get_gdrive_filename.R")
  source("./R/hexagon_coords.R")
  source("./R/load_rasters.R")
  source("./R/make_polygon.R")
  source("./R/post_to_biomastats.R")
  source("./R/square_coords.R")
}
```

```{r}
#(path_package <- system.file(package = "biomasync"))
#path_package <- getwd()
getwd()
```

## carregando o shp de exemplo

```{r}
ufscar_shp <- "./inst/shp/UFSCar.shp"
library(mapview)
library(sf)
mapview(sf::read_sf(ufscar_shp))
```

```{r}
load_codes()
```


```{r}
recortes <- biomastats_sync(shape_path = ufscar_shp, start=1985, end=2020, export_folder_path = "./biblioteca-teste")
```

